
package sopra.processors.soap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MarketedElementEndPoint", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MarketedElementEndPoint {


    /**
     * 
     * @param marketingContext
     * @param distributionContext
     * @param customerContext
     * @param businessContext
     * @param classificationContext
     * @param detailLevel
     * @return
     *     returns sopra.processors.soap.client.ResultOfferOnSaleListDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOfferOnSaleList", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", className = "sopra.processors.soap.client.GetOfferOnSaleList")
    @ResponseWrapper(localName = "getOfferOnSaleListResponse", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", className = "sopra.processors.soap.client.GetOfferOnSaleListResponse")
    @Action(input = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/MarketedElementEndPoint/getOfferOnSaleListRequest", output = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/MarketedElementEndPoint/getOfferOnSaleListResponse")
    public ResultOfferOnSaleListDto getOfferOnSaleList(
        @WebParam(name = "businessContext", targetNamespace = "")
        BusinessContextDto businessContext,
        @WebParam(name = "distributionContext", targetNamespace = "")
        DistributionContextDto distributionContext,
        @WebParam(name = "customerContext", targetNamespace = "")
        CustomerContextDto customerContext,
        @WebParam(name = "classificationContext", targetNamespace = "")
        ClassificationContextDto classificationContext,
        @WebParam(name = "marketingContext", targetNamespace = "")
        MarketingContextDto marketingContext,
        @WebParam(name = "detailLevel", targetNamespace = "")
        DetailLevelDto detailLevel);

    /**
     * 
     * @param marketingContext
     * @param distributionContext
     * @param businessContext
     * @param equipmentList
     * @param detailLevel
     * @return
     *     returns sopra.processors.soap.client.ResultAfterSaleActListDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAfterSaleElementList", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", className = "sopra.processors.soap.client.GetAfterSaleElementList")
    @ResponseWrapper(localName = "getAfterSaleElementListResponse", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", className = "sopra.processors.soap.client.GetAfterSaleElementListResponse")
    @Action(input = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/MarketedElementEndPoint/getAfterSaleElementListRequest", output = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/MarketedElementEndPoint/getAfterSaleElementListResponse")
    public ResultAfterSaleActListDto getAfterSaleElementList(
        @WebParam(name = "businessContext", targetNamespace = "")
        BusinessContextDto businessContext,
        @WebParam(name = "distributionContext", targetNamespace = "")
        DistributionContextDto distributionContext,
        @WebParam(name = "marketingContext", targetNamespace = "")
        MarketingContextDto marketingContext,
        @WebParam(name = "equipmentList", targetNamespace = "")
        List<EquipmentDto> equipmentList,
        @WebParam(name = "detailLevel", targetNamespace = "")
        DetailLevelDto detailLevel);

    /**
     * 
     * @param marketingContext
     * @param distributionContext
     * @param customerContext
     * @param businessContext
     * @param classificationContext
     * @param equipmentList
     * @param detailLevel
     * @return
     *     returns sopra.processors.soap.client.ResultMarketedEltListDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMarketedElementList", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", className = "sopra.processors.soap.client.GetMarketedElementList")
    @ResponseWrapper(localName = "getMarketedElementListResponse", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", className = "sopra.processors.soap.client.GetMarketedElementListResponse")
    @Action(input = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/MarketedElementEndPoint/getMarketedElementListRequest", output = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/MarketedElementEndPoint/getMarketedElementListResponse")
    public ResultMarketedEltListDto getMarketedElementList(
        @WebParam(name = "businessContext", targetNamespace = "")
        BusinessContextDto businessContext,
        @WebParam(name = "distributionContext", targetNamespace = "")
        DistributionContextDto distributionContext,
        @WebParam(name = "customerContext", targetNamespace = "")
        CustomerContextDto customerContext,
        @WebParam(name = "classificationContext", targetNamespace = "")
        ClassificationContextDto classificationContext,
        @WebParam(name = "marketingContext", targetNamespace = "")
        MarketingContextDto marketingContext,
        @WebParam(name = "equipmentList", targetNamespace = "")
        List<EquipmentDto> equipmentList,
        @WebParam(name = "detailLevel", targetNamespace = "")
        DetailLevelDto detailLevel);

    /**
     * 
     * @param commercialEltIdentification
     * @param marketingContext
     * @param distributionContext
     * @param customerContext
     * @param businessContext
     * @param classificationContext
     * @param detailLevel
     * @return
     *     returns sopra.processors.soap.client.ResultOfferForCommercialEltListDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOfferOnSaleListForCommercialElt", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", className = "sopra.processors.soap.client.GetOfferOnSaleListForCommercialElt")
    @ResponseWrapper(localName = "getOfferOnSaleListForCommercialEltResponse", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", className = "sopra.processors.soap.client.GetOfferOnSaleListForCommercialEltResponse")
    @Action(input = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/MarketedElementEndPoint/getOfferOnSaleListForCommercialEltRequest", output = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/MarketedElementEndPoint/getOfferOnSaleListForCommercialEltResponse")
    public ResultOfferForCommercialEltListDto getOfferOnSaleListForCommercialElt(
        @WebParam(name = "businessContext", targetNamespace = "")
        BusinessContextDto businessContext,
        @WebParam(name = "distributionContext", targetNamespace = "")
        DistributionContextDto distributionContext,
        @WebParam(name = "customerContext", targetNamespace = "")
        CustomerContextDto customerContext,
        @WebParam(name = "classificationContext", targetNamespace = "")
        ClassificationContextDto classificationContext,
        @WebParam(name = "marketingContext", targetNamespace = "")
        MarketingContextDto marketingContext,
        @WebParam(name = "commercialEltIdentification", targetNamespace = "")
        CommercialEltIdentificationDto commercialEltIdentification,
        @WebParam(name = "detailLevel", targetNamespace = "")
        DetailLevelDto detailLevel);

}
