
package sopra.processors.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MarketedElementEndPointService", targetNamespace = "http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", wsdlLocation = "file:/C:/Users/Vincent/Desktop/Projet Big Data/Soap/MarketedElementEndPoint.wsdl")
public class MarketedElementEndPointService
    extends Service
{

    private final static URL MARKETEDELEMENTENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException MARKETEDELEMENTENDPOINTSERVICE_EXCEPTION;
    private final static QName MARKETEDELEMENTENDPOINTSERVICE_QNAME = new QName("http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", "MarketedElementEndPointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Vincent/Desktop/Projet Big Data/Soap/MarketedElementEndPoint.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MARKETEDELEMENTENDPOINTSERVICE_WSDL_LOCATION = url;
        MARKETEDELEMENTENDPOINTSERVICE_EXCEPTION = e;
    }

    public MarketedElementEndPointService() {
        super(__getWsdlLocation(), MARKETEDELEMENTENDPOINTSERVICE_QNAME);
    }

    public MarketedElementEndPointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MARKETEDELEMENTENDPOINTSERVICE_QNAME, features);
    }

    public MarketedElementEndPointService(URL wsdlLocation) {
        super(wsdlLocation, MARKETEDELEMENTENDPOINTSERVICE_QNAME);
    }

    public MarketedElementEndPointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MARKETEDELEMENTENDPOINTSERVICE_QNAME, features);
    }

    public MarketedElementEndPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarketedElementEndPointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MarketedElementEndPoint
     */
    @WebEndpoint(name = "MarketedElementEndPointPort")
    public MarketedElementEndPoint getMarketedElementEndPointPort() {
        return super.getPort(new QName("http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", "MarketedElementEndPointPort"), MarketedElementEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarketedElementEndPoint
     */
    @WebEndpoint(name = "MarketedElementEndPointPort")
    public MarketedElementEndPoint getMarketedElementEndPointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://published.service.v3_0.endpoint.catalog.evolan.sopra.com/", "MarketedElementEndPointPort"), MarketedElementEndPoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MARKETEDELEMENTENDPOINTSERVICE_EXCEPTION!= null) {
            throw MARKETEDELEMENTENDPOINTSERVICE_EXCEPTION;
        }
        return MARKETEDELEMENTENDPOINTSERVICE_WSDL_LOCATION;
    }

}
